import {useAnimationState} from 'moti'
import { height } from './dimentions';

export const Data = {
  bort: [
    { text: "01" },
    { text: "02" },
    { text: "03" },
    { text: "04" },
    { text: "05" },
    { text: "06" },
    { text: "07" },
    { text: "08" },
    { text: "09" },
    { text: "10" },
    { text: "11" },
    { text: "12" },
  ],
  image: [
    { text: "1" },
    { text: "2" },
    { text: "3" },
    { text: "4" },
    { text: "5" },
    { text: "6" },
    { text: "7" },
    { text: "8" },
    { text: "9" },
    { text: "10" },
    { text: "11" },
    { text: "12" },
    { text: "13" },
    { text: "14" },
    { text: "15" },
    { text: "16" },
    { text: "17" },
    { text: "18" },
    { text: "19" },
    { text: "20" },
    { text: "21" },
    { text: "1" },
    { text: "2" },
    { text: "3" },
    { text: "4" },
    { text: "5" },
    { text: "6" },
    { text: "7" },
    { text: "8" },
    { text: "9" },
    { text: "10" },
    { text: "11" },
    { text: "12" },
    { text: "13" },
    { text: "14" },
    { text: "15" },
    { text: "16" },
    { text: "17" },
    { text: "18" },
    { text: "19" },
    { text: "20" },
    { text: "21" },

  ],
  damage: [
    { text: "Сообщить о неисправности борта 08" },
    { text: "Сообщить о неисправности другого борта" },
  ],
  malfunction: [{ text: "Повреждений нет" }, { text: "Имеются повреждения" }],
  radio: [{ text: "Костьюм Л-1" }],
};

